# Generated by Django 4.2.24 on 2025-11-12 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('noi_dung', models.TextField(verbose_name='Nội dung')),
                ('chuyen_muc', models.CharField(max_length=100, verbose_name='Chuyên mục')),
                ('ngay_dang', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('tac_gia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
            ],
            options={
                'verbose_name': 'Bài viết Kiến thức',
                'verbose_name_plural': 'Các bài viết Kiến thức',
                'ordering': ['-ngay_dang'],
            },
        ),
    ]
