# Generated by Django 4.2.24 on 2025-11-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='anh_bia',
            field=models.ImageField(blank=True, null=True, upload_to='article_covers/', verbose_name='Ảnh bìa'),
        ),
        migrations.AddField(
            model_name='article',
            name='noi_bat',
            field=models.BooleanField(default=False, verbose_name='Đánh dấu nổi bật'),
        ),
    ]
