# Generated by Django 4.2.24 on 2025-11-12 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_article_anh_bia_article_noi_bat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiHuongDan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', models.TextField()),
                ('chuyen_muc', models.CharField(max_length=100)),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
                ('tac_gia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài viết kiến thức',
                'verbose_name_plural': 'Các bài viết kiến thức',
                'db_table': 'kien_thuc_bai_huong_dan',
                'ordering': ['-ngay_dang'],
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
