# Generated by Django 4.2.24 on 2025-11-12 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_baihuongdan_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='baihuongdan',
            name='da_duyet',
            field=models.BooleanField(default=False, verbose_name='Đã duyệt'),
        ),
        migrations.AddField(
            model_name='baihuongdan',
            name='ngay_duyet',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt'),
        ),
        migrations.AddField(
            model_name='baihuongdan',
            name='nguoi_duyet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_huong_dan_da_duyet', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AlterField(
            model_name='baihuongdan',
            name='chuyen_muc',
            field=models.CharField(max_length=100, verbose_name='Chuyên mục'),
        ),
        migrations.AlterField(
            model_name='baihuongdan',
            name='ngay_dang',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng'),
        ),
        migrations.AlterField(
            model_name='baihuongdan',
            name='noi_dung',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='baihuongdan',
            name='tac_gia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_huong_dan_da_viet', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='baihuongdan',
            name='tieu_de',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
    ]
