# Generated by Django 4.2.24 on 2025-11-15 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_baihuongdan_da_duyet_baihuongdan_ngay_duyet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuyenMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, unique=True, verbose_name='Tên chuyên mục')),
                ('slug', models.SlugField(blank=True, help_text='Tự động tạo nếu bỏ trống', max_length=110, unique=True)),
            ],
            options={
                'verbose_name': 'Chuyên mục',
                'verbose_name_plural': 'Các chuyên mục',
                'ordering': ['ten'],
            },
        ),
        migrations.AddField(
            model_name='baihuongdan',
            name='chuyen_muc_old',
            field=models.CharField(max_length=100, null=True, verbose_name='Chuyên mục cũ'),
        ),
        migrations.AlterField(
            model_name='baihuongdan',
            name='nguoi_duyet',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_huong_dan_da_duyet', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AlterField(
            model_name='baihuongdan',
            name='tac_gia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_huong_dan_da_viet', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='baihuongdan',
            name='chuyen_muc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.chuyenmuc', verbose_name='Chuyên mục'),
        ),
    ]
