# Generated by Django 4.2.24 on 2025-11-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_chuyenmuc_baihuongdan_chuyen_muc_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baihuongdan',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to='articles/thumbnails/', verbose_name='Ảnh đại diện'),
        ),
    ]
