# Generated by Django 4.2.23 on 2025-09-10 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeThongThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.CharField(max_length=255)),
                ('lien_ket', models.CharField(blank=True, max_length=255, null=True)),
                ('da_doc', models.BooleanField(default=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'he_thong_thong_bao',
                'ordering': ['-ngay_tao'],
                'indexes': [models.Index(fields=['nguoi_nhan', '-ngay_tao'], name='he_thong_th_nguoi_n_72145b_idx')],
            },
        ),
        migrations.CreateModel(
            name='HeThongBaoCao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ly_do_bao_cao', models.TextField()),
                ('ngay_bao_cao', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('trang_thai', models.CharField(choices=[('Mới', 'Mới'), ('Đang xử lý', 'Đang xử lý'), ('Đã xử lý', 'Đã xử lý')], default='Mới', max_length=20)),
                ('ghi_chu_xu_ly', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('nguoi_bao_cao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bao_cao_da_gui', to=settings.AUTH_USER_MODEL)),
                ('nguoi_xu_ly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bao_cao_da_xu_ly', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'he_thong_bao_cao',
                'ordering': ['-ngay_bao_cao'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='he_thong_ba_content_fe54bd_idx'), models.Index(fields=['trang_thai'], name='he_thong_ba_trang_t_ec3f98_idx')],
            },
        ),
    ]
