# Generated by Django 4.2.23 on 2025-09-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hethongthongbao_hethongbaocao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hethongthongbao',
            options={'ordering': ['-ngay_tao'], 'verbose_name': 'Thông báo Hệ thống', 'verbose_name_plural': 'Các Thông báo Hệ thống'},
        ),
        migrations.AddField(
            model_name='hethongthongbao',
            name='tieu_de',
            field=models.CharField(default='Thông báo hệ thống', max_length=255),
        ),
    ]
