# Generated by Django 4.2.23 on 2025-09-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hethongthongbao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hethongthongbao',
            name='tieu_de',
            field=models.CharField(default='Thông báo mới', max_length=150),
        ),
    ]
