# Generated by Django 4.2.23 on 2025-12-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_chuyendi_trang_thai'),
        ('core', '0004_alter_hethongthongbao_tieu_de'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrangThaiChuyenDi',
        ),
    ]
