# Generated by Django 4.2.23 on 2025-08-30 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongDongBaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', models.TextField()),
                ('luot_binh_chon', models.IntegerField(default=0)),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
                ('chuyen_di', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.chuyendi')),
                ('tac_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_viet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ngay_dang'],
            },
        ),
        migrations.CreateModel(
            name='CongDongMediaBaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_media', models.CharField(choices=[('Ảnh', 'Ảnh'), ('Video', 'Video')], max_length=10)),
                ('duong_dan_file', models.CharField(max_length=255)),
                ('ngay_tai_len', models.DateTimeField(auto_now_add=True)),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='community.congdongbaiviet')),
            ],
        ),
        migrations.CreateModel(
            name='CongDongBinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('ngay_binh_luan', models.DateTimeField(auto_now_add=True)),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan', to='community.congdongbaiviet')),
                ('tra_loi_binh_luan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cac_tra_loi', to='community.congdongbinhluan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ngay_binh_luan'],
            },
        ),
        migrations.CreateModel(
            name='CongDongBinhChonBaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_binh_chon', models.DateTimeField(auto_now_add=True)),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.congdongbaiviet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('bai_viet', 'user')},
            },
        ),
    ]
