<<<<<<< HEAD
# Generated by Django 4.2.23 on 2025-12-04 11:15

import community.models
=======
# Generated by Django 4.2.23 on 2025-08-30 18:52

>>>>>>> 2a3c570e2a74a83ea4beae6f32f15af4df86cb43
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< HEAD
        ('trips', '0008_remove_chuyendi_is_deleted'),
        ('core', '0005_delete_trangthaichuyendi'),
=======
        ('trips', '0001_initial'),
>>>>>>> 2a3c570e2a74a83ea4beae6f32f15af4df86cb43
    ]

    operations = [
        migrations.CreateModel(
            name='CongDongBaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('noi_dung', models.TextField(verbose_name='Nội dung')),
                ('luot_binh_chon', models.IntegerField(default=0, verbose_name='Lượt bình chọn')),
                ('ngay_dang', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('trang_thai', models.CharField(choices=[('cho_duyet', 'Chờ duyệt'), ('da_duyet', 'Đã duyệt'), ('tu_choi', 'Từ chối')], default='cho_duyet', max_length=20, verbose_name='Trạng thái')),
                ('chuyen_di', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_viet_lien_quan', to='trips.chuyendi', verbose_name='Chuyến đi')),
                ('tac_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_viet_cong_dong', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('tags', models.ManyToManyField(blank=True, related_name='bai_viet_cong_dong', to='core.the', verbose_name='Các thẻ')),
            ],
            options={
                'verbose_name': 'Bài viết cộng đồng',
                'verbose_name_plural': 'Các bài viết cộng đồng',
                'db_table': 'community_congdongbaiviet',
=======
                ('tieu_de', models.CharField(max_length=255)),
                ('noi_dung', models.TextField()),
                ('luot_binh_chon', models.IntegerField(default=0)),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
                ('chuyen_di', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.chuyendi')),
                ('tac_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_viet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
>>>>>>> 2a3c570e2a74a83ea4beae6f32f15af4df86cb43
                'ordering': ['-ngay_dang'],
            },
        ),
        migrations.CreateModel(
            name='CongDongMediaBaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('loai_media', models.CharField(choices=[('anh', 'Ảnh'), ('video', 'Video')], max_length=10, verbose_name='Loại media')),
                ('duong_dan_file', models.FileField(upload_to=community.models.tao_duong_dan_media, verbose_name='File')),
                ('ngay_tai_len', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='community.congdongbaiviet', verbose_name='Bài viết')),
            ],
            options={
                'verbose_name': 'Media bài viết',
                'verbose_name_plural': 'Media các bài viết',
                'db_table': 'community_congdongmediabaiviet',
                'ordering': ['ngay_tai_len'],
            },
=======
                ('loai_media', models.CharField(choices=[('Ảnh', 'Ảnh'), ('Video', 'Video')], max_length=10)),
                ('duong_dan_file', models.CharField(max_length=255)),
                ('ngay_tai_len', models.DateTimeField(auto_now_add=True)),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='community.congdongbaiviet')),
            ],
>>>>>>> 2a3c570e2a74a83ea4beae6f32f15af4df86cb43
        ),
        migrations.CreateModel(
            name='CongDongBinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('noi_dung', models.TextField(verbose_name='Nội dung')),
                ('ngay_binh_luan', models.DateTimeField(auto_now_add=True, verbose_name='Ngày bình luận')),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan', to='community.congdongbaiviet', verbose_name='Bài viết')),
                ('tra_loi_binh_luan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cac_tra_loi', to='community.congdongbinhluan', verbose_name='Trả lời bình luận')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan_cong_dong', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Các bình luận',
                'db_table': 'community_congdongbinhluan',
=======
                ('noi_dung', models.TextField()),
                ('ngay_binh_luan', models.DateTimeField(auto_now_add=True)),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan', to='community.congdongbaiviet')),
                ('tra_loi_binh_luan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cac_tra_loi', to='community.congdongbinhluan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
>>>>>>> 2a3c570e2a74a83ea4beae6f32f15af4df86cb43
                'ordering': ['ngay_binh_luan'],
            },
        ),
        migrations.CreateModel(
            name='CongDongBinhChonBaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('ngay_binh_chon', models.DateTimeField(auto_now_add=True, verbose_name='Ngày bình chọn')),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_chon', to='community.congdongbaiviet', verbose_name='Bài viết')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_chon_bai_viet', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Bình chọn bài viết',
                'verbose_name_plural': 'Các bình chọn bài viết',
                'db_table': 'community_congdongbinhchonbaiviet',
                'unique_together': {('bai_viet', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='congdongbaiviet',
            index=models.Index(fields=['-ngay_dang'], name='community_c_ngay_da_cb469b_idx'),
        ),
        migrations.AddIndex(
            model_name='congdongbaiviet',
            index=models.Index(fields=['trang_thai'], name='community_c_trang_t_08eebe_idx'),
        ),
=======
                ('ngay_binh_chon', models.DateTimeField(auto_now_add=True)),
                ('bai_viet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.congdongbaiviet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('bai_viet', 'user')},
            },
        ),
>>>>>>> 2a3c570e2a74a83ea4beae6f32f15af4df86cb43
    ]
