# Generated by Django 4.2.24 on 2025-10-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_hethongthongbao_tieu_de'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='congdongbaiviet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bai_viet_cong_dong', to='core.the', verbose_name='Các thẻ'),
        ),
    ]
