# Generated by Django 4.2.24 on 2025-10-15 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_hethongthongbao_tieu_de'),
        ('trips', '0001_initial'),
        ('community', '0002_congdongbaiviet_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congdongbaiviet',
            options={'ordering': ['-da_ghim', '-ngay_dang'], 'verbose_name': 'Bài viết cộng đồng', 'verbose_name_plural': 'Các bài viết cộng đồng'},
        ),
        migrations.RemoveIndex(
            model_name='congdongbaiviet',
            name='community_c_ngay_da_cb469b_idx',
        ),
        migrations.AddField(
            model_name='congdongbaiviet',
            name='da_ghim',
            field=models.BooleanField(default=False, verbose_name='Đã ghim'),
        ),
        migrations.AlterField(
            model_name='congdongbaiviet',
            name='chuyen_di',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.chuyendi'),
        ),
        migrations.AlterField(
            model_name='congdongbaiviet',
            name='tac_gia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_viet_cong_dong', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='congdongbaiviet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bai_viet_cong_dong', to='core.the'),
        ),
    ]
