# Generated by Django 4.2.24 on 2025-10-15 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_hethongthongbao_tieu_de'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0001_initial'),
        ('community', '0003_alter_congdongbaiviet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congdongbaiviet',
            options={'ordering': ['-ngay_dang'], 'verbose_name': 'Bài viết cộng đồng', 'verbose_name_plural': 'Các bài viết cộng đồng'},
        ),
        migrations.RemoveField(
            model_name='congdongbaiviet',
            name='da_ghim',
        ),
        migrations.AlterField(
            model_name='congdongbaiviet',
            name='chuyen_di',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_viet_lien_quan', to='trips.chuyendi', verbose_name='Chuyến đi'),
        ),
        migrations.AlterField(
            model_name='congdongbaiviet',
            name='tac_gia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_viet_cong_dong', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='congdongbaiviet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bai_viet_cong_dong', to='core.the', verbose_name='Các thẻ'),
        ),
        migrations.AddIndex(
            model_name='congdongbaiviet',
            index=models.Index(fields=['-ngay_dang'], name='community_c_ngay_da_cb469b_idx'),
        ),
    ]
