# Generated by Django 4.2.24 on 2025-12-01 14:48

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_congdongbaiviet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congdongmediabaiviet',
            name='duong_dan_file',
            field=models.FileField(upload_to=community.models.tao_duong_dan_media, verbose_name='File'),
        ),
    ]
