# Generated by Django 4.2.23 on 2025-08-30 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoanHoSo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('anh_dai_dien', models.CharField(blank=True, max_length=200, null=True)),
                ('gioi_thieu', models.TextField(blank=True, null=True)),
                ('diem_thuong', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoanThietBiCaNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=1)),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vat_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vatdung')),
            ],
            options={
                'unique_together': {('user', 'vat_dung')},
            },
        ),
        migrations.CreateModel(
            name='TaiKhoanSoThichNguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.the')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'the')},
            },
        ),
    ]
