# Generated by Django 4.2.23 on 2025-09-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoanhoso',
            name='sdt',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
