# Generated by Django 4.2.23 on 2025-09-29 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_hethongthongbao_tieu_de'),
        ('accounts', '0002_taikhoanhoso_sdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoanhoso',
            name='tinh_thanh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tinhthanh', verbose_name='Tỉnh/Thành phố'),
        ),
    ]
