# Generated by Django 4.2.23 on 2025-09-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_taikhoanhoso_tinh_thanh'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoanhoso',
            name='gioi_tinh',
            field=models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, null=True, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='taikhoanhoso',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='taikhoanhoso',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
