# Generated by Django 4.2.23 on 2025-08-30 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CungDuongTrek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=220, unique=True)),
                ('mo_ta', models.TextField()),
                ('anh_bia', models.CharField(max_length=200)),
                ('do_dai_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thoi_gian_uoc_tinh_gio', models.IntegerField()),
                ('tong_do_cao_leo_m', models.IntegerField(blank=True, null=True)),
                ('mua_dep_nhat', models.CharField(blank=True, max_length=100, null=True)),
                ('du_lieu_ban_do_geojson', models.JSONField(blank=True, null=True)),
                ('danh_gia_trung_binh', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('so_luot_danh_gia', models.IntegerField(default=0)),
                ('da_duyet', models.BooleanField(default=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('do_kho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dokho')),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tinh_thanh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tinhthanh')),
            ],
            options={
                'verbose_name': 'Cung Đường Trek',
                'verbose_name_plural': 'Các Cung Đường Trek',
                'db_table': 'cung_duong_trek',
            },
        ),
        migrations.CreateModel(
            name='CungDuongVatDungGoiY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
                ('cung_duong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treks.cungduongtrek')),
                ('vat_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vatdung')),
            ],
            options={
                'verbose_name': 'Vật Dụng Gợi Ý',
                'verbose_name_plural': 'Các Vật Dụng Gợi Ý',
                'db_table': 'cung_duong_vat_dung_goi_y',
            },
        ),
        migrations.CreateModel(
            name='CungDuongDanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_danh_gia', models.PositiveSmallIntegerField()),
                ('binh_luan', models.TextField(blank=True, null=True)),
                ('ngay_danh_gia', models.DateTimeField(auto_now_add=True)),
                ('cung_duong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treks.cungduongtrek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đánh Giá Cung Đường',
                'verbose_name_plural': 'Các Đánh Giá Cung Đường',
                'db_table': 'cung_duong_danh_gia',
                'unique_together': {('cung_duong', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CungDuongAnhDanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.CharField(max_length=200)),
                ('danh_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treks.cungduongdanhgia')),
            ],
            options={
                'verbose_name': 'Ảnh Đánh Giá',
                'verbose_name_plural': 'Các Ảnh Đánh Giá',
                'db_table': 'cung_duong_anh_danh_gia',
            },
        ),
    ]
