# Generated by Django 4.2.23 on 2025-09-30 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_hethongthongbao_tieu_de'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cungduongdanhgia',
            options={'ordering': ['-ngay_danh_gia'], 'verbose_name': 'Đánh Giá Cung Đường', 'verbose_name_plural': 'Các Đánh Giá Cung Đường'},
        ),
        migrations.AlterModelOptions(
            name='cungduongtrek',
            options={'ordering': ['-ngay_tao'], 'verbose_name': 'Cung Đường Trek', 'verbose_name_plural': 'Các Cung Đường Trek'},
        ),
        migrations.RemoveField(
            model_name='cungduongtrek',
            name='anh_bia',
        ),
        migrations.RemoveField(
            model_name='cungduongtrek',
            name='da_duyet',
        ),
        migrations.AddField(
            model_name='cungduongtrek',
            name='ngay_cap_nhat',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='cungduongtrek',
            name='trang_thai',
            field=models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('DA_DUYET', 'Đã duyệt'), ('TU_CHOI', 'Từ chối')], default='CHO_DUYET', max_length=10, verbose_name='Trạng thái duyệt'),
        ),
        migrations.AlterField(
            model_name='cungduonganhdanhgia',
            name='danh_gia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anh_danh_gia', to='treks.cungduongdanhgia'),
        ),
        migrations.AlterField(
            model_name='cungduonganhdanhgia',
            name='hinh_anh',
            field=models.ImageField(upload_to='reviews_media/'),
        ),
        migrations.AlterField(
            model_name='cungduongdanhgia',
            name='cung_duong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='treks.cungduongtrek'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='danh_gia_trung_binh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Điểm đánh giá trung bình'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='do_dai_km',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Độ dài (km)'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='do_kho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dokho', verbose_name='Độ khó'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='du_lieu_ban_do_geojson',
            field=models.JSONField(blank=True, null=True, verbose_name='Dữ liệu bản đồ GeoJSON'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='mo_ta',
            field=models.TextField(verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='mua_dep_nhat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mùa đẹp nhất'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='nguoi_tao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='slug',
            field=models.CharField(max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='so_luot_danh_gia',
            field=models.IntegerField(default=0, verbose_name='Số lượt đánh giá'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='ten',
            field=models.CharField(max_length=200, verbose_name='Tên cung đường'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='thoi_gian_uoc_tinh_gio',
            field=models.IntegerField(verbose_name='Thời gian ước tính (giờ)'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='tinh_thanh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tinhthanh', verbose_name='Tỉnh/Thành phố'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='tong_do_cao_leo_m',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tổng độ cao leo (m)'),
        ),
        migrations.AlterField(
            model_name='cungduongvatdunggoiy',
            name='cung_duong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_dung_goi_y', to='treks.cungduongtrek'),
        ),
        migrations.AlterUniqueTogether(
            name='cungduongvatdunggoiy',
            unique_together={('cung_duong', 'vat_dung')},
        ),
        migrations.CreateModel(
            name='CungDuongMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='treks_media/', verbose_name='Tập tin media')),
                ('loai_media', models.CharField(choices=[('ANH', 'Ảnh'), ('VIDEO', 'Video')], default='ANH', max_length=5, verbose_name='Loại media')),
                ('la_anh_bia', models.BooleanField(default=False, help_text='Đánh dấu đây là ảnh bìa chính', verbose_name='Là ảnh bìa?')),
                ('ngay_tai_len', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('cung_duong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='treks.cungduongtrek')),
            ],
            options={
                'verbose_name': 'Media Cung Đường',
                'verbose_name_plural': 'Các Media Cung Đường',
                'db_table': 'cung_duong_media',
                'ordering': ['-la_anh_bia', 'ngay_tai_len'],
            },
        ),
        migrations.CreateModel(
            name='CungDuongDuyetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanh_dong', models.CharField(choices=[('DUYET', 'Duyệt'), ('TU_CHOI', 'Từ chối')], max_length=10)),
                ('ly_do', models.TextField(blank=True, help_text='Ghi rõ lý do nếu từ chối', null=True)),
                ('ngay_thuc_hien', models.DateTimeField(auto_now_add=True)),
                ('cung_duong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_duyet', to='treks.cungduongtrek')),
                ('nguoi_thuc_hien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hanh_dong_duyet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký Duyệt Cung đường',
                'verbose_name_plural': 'Các Nhật ký Duyệt Cung đường',
                'db_table': 'cung_duong_duyet_log',
                'ordering': ['-ngay_thuc_hien'],
            },
        ),
    ]
