# Generated by Django 4.2.23 on 2025-09-30 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import treks.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treks', '0002_alter_cungduongdanhgia_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cungduongdanhgia',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='cungduongvatdunggoiy',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cungduongdanhgia',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cungduongmedia',
            name='file',
            field=models.FileField(upload_to=treks.models.get_trek_media_path, verbose_name='Tập tin media'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='slug',
            field=models.SlugField(blank=True, help_text='Để trống để tự động tạo từ tên.', max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AddConstraint(
            model_name='cungduongdanhgia',
            constraint=models.UniqueConstraint(fields=('cung_duong', 'user'), name='unique_user_review_per_trek'),
        ),
        migrations.AddConstraint(
            model_name='cungduongvatdunggoiy',
            constraint=models.UniqueConstraint(fields=('cung_duong', 'vat_dung'), name='unique_trek_equipment_suggestion'),
        ),
    ]
