# Generated by Django 4.2.23 on 2025-09-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0003_alter_cungduongdanhgia_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cungduongtrek',
            name='dia_diem_chi_tiet',
            field=models.CharField(blank=True, help_text='Ví dụ: Vườn quốc gia Ba Vì, Hà Nội', max_length=255, null=True, verbose_name='Địa điểm chi tiết (để tìm trên bản đồ)'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='trang_thai',
            field=models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('DA_DUYET', 'Đã duyệt'), ('TU_CHOI', 'Từ chối')], default='DA_DUYET', max_length=10, verbose_name='Trạng thái duyệt'),
        ),
    ]
