# Generated by Django 4.2.23 on 2025-10-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0004_cungduongtrek_dia_diem_chi_tiet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cungduongtrek',
            name='dia_diem_chi_tiet',
        ),
        migrations.RemoveField(
            model_name='cungduongtrek',
            name='du_lieu_ban_do_geojson',
        ),
        migrations.AddField(
            model_name='cungduongtrek',
            name='kinh_do',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kinh độ (Longitude)'),
        ),
        migrations.AddField(
            model_name='cungduongtrek',
            name='vi_do',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Vĩ độ (Latitude)'),
        ),
    ]
