# Generated by Django 4.2.23 on 2025-10-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0005_remove_cungduongtrek_dia_diem_chi_tiet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cungduongtrek',
            name='kinh_do',
        ),
        migrations.RemoveField(
            model_name='cungduongtrek',
            name='vi_do',
        ),
        migrations.AddField(
            model_name='cungduongtrek',
            name='dia_diem_chi_tiet',
            field=models.CharField(blank=True, help_text='Ví dụ: Vườn quốc gia Ba Vì, Hà Nội', max_length=255, null=True, verbose_name='Địa điểm chi tiết (để tìm trên bản đồ)'),
        ),
        migrations.AddField(
            model_name='cungduongtrek',
            name='du_lieu_ban_do_geojson',
            field=models.JSONField(blank=True, null=True, verbose_name='Dữ liệu bản đồ GeoJSON'),
        ),
    ]
