# Generated by Django 4.2.23 on 2025-11-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0006_remove_cungduongtrek_kinh_do_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cungduongtrek',
            name='do_dai_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Độ dài (km)'),
        ),
    ]
