# Generated by Django 4.2.23 on 2025-11-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_hethongthongbao_tieu_de'),
        ('treks', '0007_alter_cungduongtrek_do_dai_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cungduongtrek',
            name='do_kho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dokho', verbose_name='Độ khó'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='thoi_gian_uoc_tinh_gio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thời gian ước tính (giờ)'),
        ),
    ]
