# Generated by Django 4.2.23 on 2025-11-04 03:14

from django.db import migrations, models
import treks.models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0008_alter_cungduongtrek_do_kho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cungduonganhdanhgia',
            name='hinh_anh',
            field=models.ImageField(upload_to=treks.models.get_review_media_path, validators=[treks.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='cungduongduyetlog',
            name='ly_do',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cungduongmedia',
            name='la_anh_bia',
            field=models.BooleanField(default=False, verbose_name='Là ảnh bìa?'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='dia_diem_chi_tiet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm chi tiết'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='mo_ta',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='cungduongtrek',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug'),
        ),
    ]
