# Generated by Django 4.2.23 on 2025-11-04 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0009_alter_cungduonganhdanhgia_hinh_anh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cungduongdanhgia',
            name='ngay_danh_gia',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đánh giá'),
        ),
    ]
