# Generated by Django 4.2.24 on 2026-02-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0010_alter_cungduongdanhgia_ngay_danh_gia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cungduongtrek',
            name='da_duyet',
            field=models.BooleanField(default=False, verbose_name='Đã duyệt'),
        ),
    ]
