# Generated by Django 4.2.23 on 2025-08-30 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('treks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuyenDi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chuyen_di', models.CharField(max_length=200)),
                ('mo_ta', models.TextField(blank=True, help_text='Mô tả chi tiết, lịch trình, yêu cầu cho chuyến đi', null=True)),
                ('ngay_bat_dau', models.DateTimeField()),
                ('so_luong_toi_da', models.IntegerField()),
                ('che_do_rieng_tu', models.CharField(choices=[('Công khai', 'Công khai'), ('Riêng tư', 'Riêng tư')], default='Công khai', max_length=15)),
                ('ma_moi', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('cung_duong', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='treks.cungduongtrek')),
                ('nguoi_to_chuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuyen_di_da_to_chuc', to=settings.AUTH_USER_MODEL)),
                ('trang_thai', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.trangthaichuyendi')),
            ],
        ),
        migrations.CreateModel(
            name='ChuyenDiTinNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('thoi_gian_gui', models.DateTimeField(auto_now_add=True)),
                ('chuyen_di', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan', to='trips.chuyendi')),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tra_loi_tin_nhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_tra_loi', to='trips.chuyenditinnhan')),
            ],
            options={
                'ordering': ['thoi_gian_gui'],
            },
        ),
        migrations.CreateModel(
            name='ChuyenDiTinNhanMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_media', models.CharField(choices=[('Ảnh', 'Ảnh'), ('Video', 'Video'), ('File', 'File')], max_length=10)),
                ('duong_dan_file', models.CharField(max_length=255)),
                ('thu_tu', models.PositiveSmallIntegerField(default=0)),
                ('ten_file_goc', models.CharField(blank=True, max_length=255, null=True)),
                ('kich_thuoc_file_kb', models.IntegerField(blank=True, null=True)),
                ('tin_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='trips.chuyenditinnhan')),
            ],
        ),
        migrations.CreateModel(
            name='ChuyenDiThanhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vai_tro', models.CharField(choices=[('Trưởng đoàn', 'Trưởng đoàn'), ('Thành viên', 'Thành viên')], default='Thành viên', max_length=15)),
                ('trang_thai_tham_gia', models.CharField(choices=[('Chờ duyệt', 'Chờ duyệt'), ('Đã duyệt', 'Đã duyệt'), ('Từ chối', 'Từ chối')], default='Chờ duyệt', max_length=15)),
                ('ngay_tham_gia', models.DateTimeField(auto_now_add=True, null=True)),
                ('chuyen_di', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanh_vien', to='trips.chuyendi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuyen_di_da_tham_gia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('chuyen_di', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChuyenDiNhatKyHanhTrinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vi_do', models.DecimalField(decimal_places=6, max_digits=9)),
                ('kinh_do', models.DecimalField(decimal_places=6, max_digits=9)),
                ('do_cao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('noi_dung_checkin', models.CharField(blank=True, max_length=255, null=True)),
                ('hinh_anh_checkin', models.CharField(blank=True, max_length=255, null=True)),
                ('thoi_gian_checkin', models.DateTimeField(auto_now_add=True)),
                ('chuyen_di', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.chuyendi')),
                ('thanh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.chuyendithanhvien')),
            ],
            options={
                'ordering': ['thoi_gian_checkin'],
            },
        ),
    ]
