# Generated by Django 4.2.23 on 2025-11-09 13:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import trips.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0010_alter_cungduongdanhgia_ngay_danh_gia'),
        ('core', '0004_alter_hethongthongbao_tieu_de'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chuyendithanhvien',
            options={'ordering': ['-vai_tro', 'ngay_tham_gia']},
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='cd_do_dai_km',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='cd_do_kho_ten',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='cd_du_lieu_ban_do_geojson',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='cd_mo_ta',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='cd_ten',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='cd_thoi_gian_uoc_tinh_gio',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='cd_tinh_thanh_ten',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='cd_tong_do_cao_leo_m',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='chi_phi_uoc_tinh',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Chi phí ước tính (VND)'),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='dia_diem_tap_trung',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm tập trung'),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='ngay_cap_nhat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='ngay_ket_thuc',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày kết thúc'),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='slug',
            field=models.SlugField(blank=True, help_text='Tự động tạo', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.the', verbose_name='Hashtag'),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='toa_do_tap_trung',
            field=models.JSONField(blank=True, help_text="Lưu dưới dạng {'lat': ..., 'lng': ...}", null=True, verbose_name='Tọa độ tập trung'),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='yeu_cau_ly_do',
            field=models.BooleanField(default=False, verbose_name='Yêu cầu lý do tham gia?'),
        ),
        migrations.AddField(
            model_name='chuyendithanhvien',
            name='ly_do_tham_gia',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do tham gia'),
        ),
        migrations.AddField(
            model_name='chuyendithanhvien',
            name='ngay_bat_dau_hanh_trinh',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu hành trình'),
        ),
        migrations.AddField(
            model_name='chuyendithanhvien',
            name='ngay_ket_thuc_hanh_trinh',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc hành trình'),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='che_do_rieng_tu',
            field=models.CharField(choices=[('CONG_KHAI', 'Công khai'), ('RIENG_TU', 'Riêng tư')], default='CONG_KHAI', max_length=15, verbose_name='Chế độ riêng tư'),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='cung_duong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chuyendi', to='treks.cungduongtrek', verbose_name='Cung đường gốc'),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='ma_moi',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Mã mời cho chuyến đi riêng tư', unique=True),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='mo_ta',
            field=models.TextField(blank=True, help_text='Mô tả chi tiết, lịch trình, yêu cầu cho chuyến đi', null=True, verbose_name='Mô tả & Kế hoạch'),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='ngay_bat_dau',
            field=models.DateTimeField(verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='nguoi_to_chuc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuyendi_da_to_chuc', to=settings.AUTH_USER_MODEL, verbose_name='Người tổ chức'),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='so_luong_toi_da',
            field=models.PositiveIntegerField(verbose_name='Số lượng tối đa'),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='ten_chuyen_di',
            field=models.CharField(max_length=200, verbose_name='Tên chuyến đi'),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='trang_thai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.trangthaichuyendi', verbose_name='Trạng thái chuyến đi'),
        ),
        migrations.AlterField(
            model_name='chuyendinhatkyhanhtrinh',
            name='hinh_anh_checkin',
            field=models.ImageField(blank=True, null=True, upload_to='trip_checkins/'),
        ),
        migrations.AlterField(
            model_name='chuyendithanhvien',
            name='ngay_tham_gia',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 9, 13, 52, 2, 265386, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chuyendithanhvien',
            name='trang_thai_tham_gia',
            field=models.CharField(choices=[('DA_GUI_YEU_CAU', 'Đã gửi yêu cầu'), ('DA_THAM_GIA', 'Đã tham gia'), ('BI_TU_CHOI', 'Bị từ chối'), ('DA_ROI_DI', 'Đã rời đi')], default='DA_GUI_YEU_CAU', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='chuyendithanhvien',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_chuyen_di', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chuyendithanhvien',
            name='vai_tro',
            field=models.CharField(choices=[('TRUONG_DOAN', 'Trưởng đoàn'), ('THANH_VIEN', 'Thành viên')], default='THANH_VIEN', max_length=15, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='chuyenditinnhanmedia',
            name='duong_dan_file',
            field=models.FileField(upload_to='trip_chat_media/'),
        ),
        migrations.AlterField(
            model_name='chuyenditinnhanmedia',
            name='loai_media',
            field=models.CharField(choices=[('ANH', 'Ảnh'), ('VIDEO', 'Video'), ('FILE', 'File')], max_length=10),
        ),
        migrations.CreateModel(
            name='ChuyenDiTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.PositiveIntegerField(verbose_name='Ngày thứ')),
                ('thoi_gian', models.TimeField(verbose_name='Thời gian')),
                ('hoat_dong', models.CharField(max_length=255, verbose_name='Hoạt động')),
                ('mo_ta_chi_tiet', models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết')),
                ('thu_tu', models.PositiveIntegerField(default=0)),
                ('chuyen_di', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='trips.chuyendi')),
            ],
            options={
                'ordering': ['ngay', 'thoi_gian', 'thu_tu'],
            },
        ),
        migrations.CreateModel(
            name='ChuyenDiMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=trips.models.trip_media_path, verbose_name='Tập tin')),
                ('loai_media', models.CharField(choices=[('ANH', 'Ảnh'), ('VIDEO', 'Video')], default='ANH', max_length=10, verbose_name='Loại media')),
                ('ngay_tai_len', models.DateTimeField(auto_now_add=True)),
                ('chuyen_di', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='trips.chuyendi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
            ],
            options={
                'ordering': ['-ngay_tai_len'],
            },
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='anh_bia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trips.chuyendimedia', verbose_name='Ảnh bìa chuyến đi'),
        ),
    ]
