# Generated by Django 4.2.23 on 2025-11-25 13:25

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import trips.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_hethongthongbao_tieu_de'),
        ('trips', '0002_alter_chuyendithanhvien_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chuyendi',
            options={'ordering': ['-ngay_bat_dau'], 'verbose_name': 'Chuyến đi', 'verbose_name_plural': 'Danh sách Chuyến đi'},
        ),
        migrations.AlterModelOptions(
            name='chuyendimedia',
            options={'ordering': ['-ngay_tai_len'], 'verbose_name': 'Media Chuyến đi'},
        ),
        migrations.AlterModelOptions(
            name='chuyendithanhvien',
            options={'ordering': ['-vai_tro', 'ngay_tham_gia'], 'verbose_name': 'Thành viên'},
        ),
        migrations.AlterModelOptions(
            name='chuyenditimeline',
            options={'ordering': ['ngay', 'thoi_gian', 'thu_tu'], 'verbose_name': 'Lịch trình', 'verbose_name_plural': 'Lịch trình chi tiết'},
        ),
        migrations.AlterUniqueTogether(
            name='chuyendithanhvien',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Đánh dấu đã xóa thay vì xóa thật.', verbose_name='Đã xóa mềm'),
        ),
        migrations.AddField(
            model_name='chuyendithanhvien',
            name='ngay_checkin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian Check-in'),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='anh_bia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trips.chuyendimedia', verbose_name='Ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='cd_do_dai_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='cd_du_lieu_ban_do_geojson',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='che_do_rieng_tu',
            field=models.CharField(choices=[('CONG_KHAI', 'Công khai'), ('RIENG_TU', 'Riêng tư')], default='CONG_KHAI', max_length=15, verbose_name='Chế độ'),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='chi_phi_uoc_tinh',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Chi phí (VND)'),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='ma_moi',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='mo_ta',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả & Kế hoạch'),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL thân thiện, tự động tạo.', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='toa_do_tap_trung',
            field=models.JSONField(blank=True, default=dict, verbose_name='Tọa độ tập trung'),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='trang_thai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.trangthaichuyendi', verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='chuyendimedia',
            name='file',
            field=models.FileField(upload_to=trips.models.trip_media_path, validators=[trips.models.validate_file_size], verbose_name='Tập tin'),
        ),
        migrations.AlterField(
            model_name='chuyenditimeline',
            name='thu_tu',
            field=models.PositiveIntegerField(default=0, help_text='Dùng để sắp xếp thứ tự hiển thị'),
        ),
        migrations.AlterField(
            model_name='chuyenditinnhanmedia',
            name='duong_dan_file',
            field=models.FileField(upload_to='trip_chat_media/', validators=[trips.models.validate_file_size]),
        ),
        migrations.AddIndex(
            model_name='chuyendinhatkyhanhtrinh',
            index=models.Index(fields=['chuyen_di', 'thoi_gian_checkin'], name='trips_chuye_chuyen__020263_idx'),
        ),
        migrations.AddIndex(
            model_name='chuyendinhatkyhanhtrinh',
            index=models.Index(fields=['vi_do', 'kinh_do'], name='trips_chuye_vi_do_f3efcf_idx'),
        ),
        migrations.AddIndex(
            model_name='chuyenditinnhan',
            index=models.Index(fields=['chuyen_di', 'thoi_gian_gui'], name='trips_chuye_chuyen__dec37c_idx'),
        ),
        migrations.AddConstraint(
            model_name='chuyendithanhvien',
            constraint=models.UniqueConstraint(fields=('chuyen_di', 'user'), name='unique_thanh_vien_chuyen_di'),
        ),
        migrations.RemoveField(
            model_name='chuyendithanhvien',
            name='ngay_bat_dau_hanh_trinh',
        ),
        migrations.RemoveField(
            model_name='chuyendithanhvien',
            name='ngay_ket_thuc_hanh_trinh',
        ),
    ]
