# Generated by Django 4.2.23 on 2025-11-30 08:15

from django.conf import settings
from django.db import migrations, models
import trips.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0003_alter_chuyendi_options_alter_chuyendimedia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chuyenditinnhan',
            name='da_xoa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chuyenditinnhan',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chuyenditinnhan',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chuyenditinnhanmedia',
            name='duong_dan_file',
            field=models.FileField(upload_to=trips.models.chat_media_path, validators=[trips.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='chuyenditinnhanmedia',
            name='kich_thuoc_file_kb',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chuyenditinnhanmedia',
            name='loai_media',
            field=models.CharField(choices=[('ANH', 'Ảnh'), ('VIDEO', 'Video'), ('FILE', 'File')], default='ANH', max_length=10),
        ),
    ]
