# Generated by Django 4.2.23 on 2025-12-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_chuyenditinnhan_da_xoa_chuyenditinnhan_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuyendi',
            name='trang_thai',
            field=models.CharField(choices=[('DANG_TUYEN', 'Đang tuyển thành viên'), ('DA_HUY', 'Đã hủy chuyến'), ('TAM_HOAN', 'Tạm hoãn')], default='DANG_TUYEN', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
