# Generated by Django 4.2.23 on 2025-12-04 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0005_alter_chuyendi_trang_thai'),
    ]

    operations = [
        migrations.AddField(
            model_name='chuyendi',
            name='ly_do_tu_choi',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do từ chối'),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='ngay_duyet',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt'),
        ),
        migrations.AddField(
            model_name='chuyendi',
            name='nguoi_duyet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chuyendi',
            name='trang_thai',
            field=models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('DANG_TUYEN', 'Đang tuyển thành viên'), ('BI_TU_CHOI', 'Bị từ chối'), ('DA_HUY', 'Đã hủy chuyến'), ('TAM_HOAN', 'Tạm hoãn')], default='CHO_DUYET', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
