# Generated by Django 4.2.23 on 2025-12-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_chuyendi_ly_do_tu_choi_chuyendi_ngay_duyet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuyendi',
            name='trang_thai',
            field=models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('DANG_TUYEN', 'Đang tuyển thành viên'), ('BI_TU_CHOI', 'Bị từ chối'), ('DA_HUY', 'Đã hủy chuyến'), ('DA_DONG', 'Đã đóng đăng ký'), ('TAM_HOAN', 'Tạm hoãn')], default='CHO_DUYET', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
