# Generated by Django 4.2.23 on 2025-12-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_chuyendi_trang_thai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chuyendi',
            name='is_deleted',
        ),
    ]
