# Generated by Django 4.2.23 on 2025-08-30 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHuyHieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, unique=True)),
                ('mo_ta', models.TextField()),
                ('anh_huy_hieu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GameHuyHieuNguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dat_duoc', models.DateTimeField(auto_now_add=True)),
                ('huy_hieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.gamehuyhieu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'huy_hieu')},
            },
        ),
    ]
