# Generated by Django 4.2.23 on 2025-12-02 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamehuyhieu',
            options={'verbose_name': 'Huy Hiệu', 'verbose_name_plural': 'Quản lý Huy Hiệu'},
        ),
        migrations.AlterModelOptions(
            name='gamehuyhieunguoidung',
            options={'verbose_name': 'Huy hiệu người dùng', 'verbose_name_plural': 'Danh sách người dùng đạt huy hiệu'},
        ),
        migrations.AddField(
            model_name='gamehuyhieu',
            name='bien_so_phu',
            field=models.CharField(blank=True, help_text="Nhập slug của tag (vd: 'san-may'), độ khó (vd: 'kho'), hoặc để trống nếu không cần.", max_length=100, null=True, verbose_name='Biến số phụ (Slug/Tag/Code)'),
        ),
        migrations.AddField(
            model_name='gamehuyhieu',
            name='gia_tri_muc_tieu',
            field=models.IntegerField(default=1, help_text='Con số cần đạt được (Ví dụ: 5 chuyến, 100km, 1 lần).', verbose_name='Giá trị mục tiêu'),
        ),
        migrations.AddField(
            model_name='gamehuyhieu',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang kích hoạt'),
        ),
        migrations.AddField(
            model_name='gamehuyhieu',
            name='loai_dieu_kien',
            field=models.CharField(choices=[('COUNT_TRIPS', 'Số chuyến đi tham gia (Người tham gia)'), ('COUNT_HOSTED_TRIPS', 'Số chuyến đi tổ chức (Host)'), ('COUNT_POSTS', 'Số bài viết cộng đồng'), ('COUNT_COMMENTS', 'Số bình luận đã viết'), ('COUNT_MESSAGES', 'Số tin nhắn đã gửi'), ('COUNT_PHOTOS', 'Số hình ảnh đã tải lên'), ('COUNT_REVIEWS', 'Số đánh giá cung đường đã viết'), ('COUNT_CHECKINS', 'Số lần check-in nhật ký hành trình'), ('COUNT_ITEMS', 'Số món đồ trong trang bị cá nhân'), ('COUNT_COLLECTED_BADGES', 'Số huy hiệu khác đã đạt được'), ('SUM_DISTANCE', 'Tổng quãng đường trekking (km)'), ('SUM_ELEVATION', 'Tổng độ cao đã leo (m)'), ('SUM_VOTES_RECEIVED', 'Tổng lượt thích/bình chọn nhận được'), ('SUM_REPLIES_RECEIVED', 'Tổng lượt phản hồi nhận được'), ('HAS_TAG_COUNT', 'Tham gia chuyến đi có Tag cụ thể (Cần nhập biến số phụ)'), ('VISIT_PROVINCE_COUNT', 'Số tỉnh thành khác nhau đã đặt chân đến'), ('FULL_PROFILE', 'Đã cập nhật đầy đủ hồ sơ (Avatar, SĐT, Giới thiệu...)'), ('NO_CANCEL_STREAK', 'Chuỗi chuyến đi tổ chức không bị hủy (cho Host)'), ('PUNCTUALITY_STREAK', 'Chuỗi check-in đúng giờ liên tiếp'), ('DIFFICULTY_LEVEL', 'Hoàn thành cung đường độ khó cụ thể (Cần nhập biến số phụ)'), ('MAX_PARTICIPANTS', 'Tổ chức chuyến đi đạt tối đa số người'), ('APPROVED_CONTRIBUTION', 'Đóng góp cung đường mới được duyệt')], default='COUNT_TRIPS', help_text='Hệ thống sẽ dựa vào loại này để tính toán.', max_length=50, verbose_name='Loại điều kiện'),
        ),
        migrations.AddField(
            model_name='gamehuyhieu',
            name='toan_tu',
            field=models.CharField(choices=[('GTE', 'Lớn hơn hoặc bằng (>=)'), ('EQ', 'Bằng chính xác (==)')], default='GTE', max_length=10, verbose_name='Toán tử so sánh'),
        ),
        migrations.AlterField(
            model_name='gamehuyhieu',
            name='anh_huy_hieu',
            field=models.CharField(max_length=200, verbose_name='Đường dẫn ảnh/Icon'),
        ),
        migrations.AlterField(
            model_name='gamehuyhieu',
            name='mo_ta',
            field=models.TextField(verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='gamehuyhieu',
            name='ten',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên huy hiệu'),
        ),
        migrations.AlterField(
            model_name='gamehuyhieunguoidung',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL),
        ),
    ]
