# Generated by Django 4.2.23 on 2025-12-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_gamehuyhieu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehuyhieu',
            name='anh_huy_hieu',
            field=models.ImageField(default='badges/default.png', upload_to='badges/', verbose_name='Ảnh huy hiệu'),
        ),
    ]
