# Generated by Django 4.2.23 on 2025-12-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_remove_gamehuyhieu_toan_tu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehuyhieu',
            name='loai_dieu_kien',
            field=models.CharField(choices=[('COUNT_TRIPS', 'Số chuyến đi tham gia'), ('COUNT_HOSTED_TRIPS', 'Số chuyến đi tổ chức'), ('COUNT_POSTS', 'Số bài viết cộng đồng'), ('COUNT_COMMENTS', 'Số bình luận'), ('COUNT_MESSAGES', 'Số tin nhắn'), ('COUNT_PHOTOS', 'Số hình ảnh tải lên'), ('COUNT_REVIEWS', 'Số đánh giá cung đường'), ('COUNT_ITEMS', 'Số món đồ trang bị'), ('COUNT_COLLECTED_BADGES', 'Số huy hiệu đã đạt'), ('SUM_DISTANCE', 'Tổng quãng đường (km)'), ('SUM_ELEVATION', 'Tổng độ cao leo (m)'), ('HAS_TAG_COUNT', 'Tham gia chuyến đi có Tag (slug)'), ('VISIT_PROVINCE_COUNT', 'Số tỉnh thành đã đến'), ('DIFFICULTY_LEVEL', 'Độ khó cung đường (tên độ khó)')], default='COUNT_TRIPS', max_length=50, verbose_name='Loại điều kiện'),
        ),
    ]
